version: "3"

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3001:3001
    volumes:
      - .:/home/node/app
    networks:
      - private-network

networks:
  private-network:
    external: true
